collections:
  - name: community.general.ufw
    source: https://galaxy.ansible.com
  - name: community.crypto.openssl_privatekey
    source: https://galaxy.ansible.com
  - name: community.crypto.openssl_publickey
    source: https://galaxy.ansible.com
  - name: community.crypto.openssl_csr
    source: https://galaxy.ansible.com
  - name: community.crypto.x509_certificate
    source: https://galaxy.ansible.com
