services:
  - docker

before_install:
  - docker pull cytopia/ansible-lint

script:
  - ls
  - docker run --rm -v $(pwd):/data cytopia/ansible-lint test.yml
  - docker run --rm -v $(pwd):/data cytopia/ansible-lint vm-configure.yml
