---
- name: Install docker
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - name: Install docker-ce v20.10.5
    yum:
      name: docker-ce-20.10.5
      state: present
