---
- name: Take necessary steps to secure dockerd
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Install PyOpenSSL
    pip:
      name: PyOpenSSL==20.0.1

  - name: Generate CA private key (4096 bits, RSA)
    community.crypto.openssl_privatekey:
      path: /etc/ssl/docker-ca-priv.pem

  - name: Generate CA public key (4096 bits, RSA)
    community.crypto.openssl_publickey:
      path: /etc/ssl/docker-ca-pub.pem
      privatekey_path: /etc/ssl/docker-ca-priv.pem

  - name: Generate server private key (4096 bits, RSA)
    community.crypto.openssl_privatekey:
      path: /etc/ssl/docker-srv-priv.pem

  #- name: Generate OpenSSL cert sign request
  #  community.crypto.openssl_csr:
  #    path: /etc/ssl/docker-server.csr
  #    privatekey_path: /etc/ssl/docker-srv-priv.pem
  #    common_name: #TODO: Add IP addr

  #- debug: var=hostvars[inventory_hostname][ansible_eth1][ipv4][address]
