---
- name: Docker daemon config file creation and service start
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Obtain IPv4 address of VM
    shell: "set -o pipefail && ip addr | grep 192 | awk '{print $2}' | sed 's/...$//'"
    register: out
    changed_when: "out.rc != 2"

  - name: Create /etc/docker
    file:
      path: /etc/docker
      state: directory
      mode: '0644'

  - name: Add docker daemon config file in /etc/docker
    template:
      src: daemon.json
      dest: /etc/docker
      mode: '0644'

  - name: Ensure docker deamon is running
    service:
      name: docker
      enabled: yes
      state: started
