---
- name: Docker swarm manager deploy
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Install docker API manager python wrapper
    pip:
      name: docker==4.4.4

  - name: Specify docker server cert path
    shell: export DOCKER_CERT_PATH=/docker/ssl && echo $DOCKER_CERT_PATH
    when: hostname_out.stdout == 'docker1'

  - name: Initialize new swarm with docker1 as swarm manager
    community.general.docker_swarm:
      state: present
      listen_addr: "{{ ipv4_out.stdout }}:2377"
      advertise_addr: "{{ ipv4_out.stdout }}"
    when: hostname_out.stdout == 'docker1'
