---
- name: Docker swarm deploy
  hosts: all
  gather_facts: false
  become: true
  vars:
    - swarm_manager_ipv4: null
    - swarm_worker_join_token: null
  tasks:
  - name: Install docker API manager python wrapper
    pip:
      name: docker==4.4.4

  # Swarm manager config
  - name: Specify docker server cert path
    shell: export DOCKER_CERT_PATH=/docker/ssl && echo $DOCKER_TLS_VERIFY
    when: hostname_out.stdout == 'docker1'

  - name: Get swarm manager IPv4 address
    shell: "set -o pipefail && ip addr | grep 192 | awk '{print $2}' | sed 's/...$//'"
    register: swarm_manager_ipv4
    changed_when: "swarm_manager_ipv4.rc != 2"
    when: hostname_out.stdout == 'docker1'

  - name: Initialize new swarm with docker1 as swarm manager
    community.general.docker_swarm:
      state: present
      listen_addr: "{{ swarm_manager_ipv4.stdout }}:2377"
      advertise_addr: "{{ swarm_manager_ipv4.stdout }}"
    register: swarm_init_out
    when: hostname_out.stdout == 'docker1'

  - name: Register swarm worker join token
    set_fact:
      swarm_worker_join_token: "{{ swarm_init_out.swarm_facts.JoinTokens.Worker }}"
    when: hostname_out.stdout == 'docker1'

  # Join swarm nodes
  - name: Wait for swarm manager to be available
    wait_for:
      host: "{{ swarm_manager_ipv4.stdout }}"
      port: 2377
      state: started
      connect_timeout: 5
      timeout: 60
    when: hostname_out.stdout != 'docker1'

  - name: Add worker node to swarm
    community.general.docker_swarm:
      state: join
      join_token: "{{ swarm_worker_join_token }}"
      remote_addrs: ["{{ swarm_manager_ipv4 }}:2377"]
      advertise_addr: "{{ ipv4_out.stdout }}"
    when: hostname_out.stdout != 'docker1'
