---
- name: Docker swarm deploy
  hosts: all
  gather_facts: false
  become: true
  tasks:
  # Swarm manager config
  - name: Specify docker server cert path
    shell: export DOCKER_CERT_PATH=/docker/ssl && echo $DOCKER_TLS_VERIFY
    when: hostname_out.stdout == 'docker1'

  - name: Initialize new swarm on docker1
    community.general.docker_swarm:
      state: present
      listen_addr: "{{ ipv4_out.stdout }}:2377"
      advertise_addr: "{{ ipv4_out.stdout }}"
    when: hostname_out.stdout == 'docker1'
