---
- name: Docker swarm workers deploy
  hosts: all
  gather_facts: false
  become: true
  vars_prompt:
  - name: swarm_worker_join_token
    prompt: Input worker join token here
  - name: swarm_manager_ipv4
    prompt: Input swarm manager IPv4 address here
  tasks:
  # Join swarm nodes
  - name: Add worker node to swarm
    community.general.docker_swarm:
      state: join
      join_token: "{{ swarm_worker_join_token }}"
      remote_addrs: ["{{ swarm_manager_ipv4 }}:2377"]
      advertise_addr: "{{ ipv4_out.stdout }}"
    when: hostname_out.stdout != 'docker1'
