---
- name: Docker swarm worker deploy
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Copy worker join token from swarm manager through docker
    command: docker --tlsverify -H 192.168.100.10:2376 swarm join-token worker -q
    register: worker_token_out
    when: hostname_out.stdout != 'docker1'

  - name: Join swarm worker
    community.general.docker_swarm:
      state: join
      join_token: "{{ worker_token_out.stdout }}"
      remote_addrs: ["192.168.100.10:2377"]
      advertise_addr: "{{ ipv4_out.stdout }}"
    when: hostname_out.stdout != 'docker1'
