---
- name: Docker swarm worker deploy
  hosts: all
  gather_facts: false
  become: true
  tasks:
  # TODO: Rethink approach to this - find a way to share join token through Ansible
  # Retrieve worker join token
  - name: Temporarily include SSH key to SSH to swarm manager
    template:
      src: "ssh-keys/private-key.txt"
      dest: /tmp/privkey
      mode: '0400'
    when: hostname_out.stdout != 'docker1'

  # TODO: Rethink approach to this - find a way to not hardcode manager IP addr - Ansible inventory?
  - name: Retrieve token via SSH
    shell: set -o pipefail && sudo ssh vagrant@192.168.100.10 -i /tmp/privkey sudo docker swarm join-token worker \
           | sed -n 3p | awk '{print $5}'
    register: token_out
    when: hostname_out.stdout != 'docker1'

  # TODO: Rethink approach to this - find a way to not hardcode manager IP addr - Ansible inventory?
  # Join swarm nodes
  - name: Add worker node to swarm
    community.general.docker_swarm:
      state: join
      join_token: "{{ token_out.stdout }}"
      remote_addrs: ["192.168.100.10:2377"]
      advertise_addr: "{{ ipv4_out.stdout }}"
    when: hostname_out.stdout != 'docker1'
