---
  - import_playbook: 02-vm-disk-config.yml
  - import_playbook: 03-vm-docker-install.yml
  - import_playbook: 04-vm-firewall-conf.yml
  - import_playbook: 05-vm-dockerd-secure.yml
  - import_playbook: 06-vm-dockerd-expose.yml
