- name: Configure docker swarm virtual machine
  hosts: all
  gather_facts: false
  tasks:
  - name: Get main block device size
    shell: parted -l | grep GB | awk '{ print $3 }' | head -n1 | tr -d GB
    register: parted_cmd_res
    changed_when: "parted_cmd_res.rc != 2"

  - name: Block device size check (Fail if under 40GB)
    fail:
      msg: "VM's disk is under 40GB, consider increasing it in your Vagrantfile \
            (https://github.com/sprotheroe/vagrant-disksize) or via your hypervisor's interface"
    when: parted_cmd_res.stdout < 40

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: yes

  - name: Install latest version of Docker
    yum:
      name: docker-ce
      state: latest
    become: yes

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
    become: yes
