- name: Configure docker swarm virtual machine
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Partition and format
    community.general.parted:
      device: /dev/sda
      number: 2
      state: present
      part_end: 1GB
      fs_type: ext4
