- name: Configure docker swarm virtual machine
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Install community.general galaxy collection
    command: ansible-galaxy collection install community.general
